name: CI Pipeline for tpmp-lab4

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  BUILD_TYPE: Debug

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential lcov gcovr libsqlite3-dev
    
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build
      run: |
        cd build
        make -j$(nproc)
    
    - name: Run tests
      run: |
        cd build
        touch greenhouse.db
        ct  est --output-on-failure -C ${{env.BUILD_TYPE}}
  
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SQLite3 via vcpkg
      run: |
        vcpkg install sqlite3:x64-windows
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
    
    - name: Build
      run: |
        cd build
        cmake --build . --config ${{env.BUILD_TYPE}}
    
    - name: Run tests
      run: |
        cd build
        echo $null >> greenhouse.db
        ctest --output-on-failure -C ${{env.BUILD_TYPE}}
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install cmake sqlite3
    
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSQLite3_INCLUDE_DIR=/opt/homebrew/opt/sqlite/include -DSQLite3_LIBRARY=/opt/homebrew/opt/sqlite/lib/libsqlite3.dylib
    
    - name: Build
      run: |
        cd build
        make -j$(sysctl -n hw.ncpu)
    
    - name: Run tests
      run: |
        cd build
        touch greenhouse.db
        ctest --output-on-failure -C ${{env.BUILD_TYPE}}